version: '3'

services:
  broker-service:
    build:
      context: ./../broker-service
      dockerfile: ./../broker-service/broker-service.dockerfile
    restart: always
    ports:
      - '8080:80'
    deploy:
      mode: replicated
      replicas: 1

  logger-service:
    build:
      context: ./../logger-service
      dockerfile: ./../logger-service/logger-service.dockerfile
    restart: always
    deploy:
      mode: replicated
      replicas: 1

  authentication-service:
    build:
      context: ./../authentication-service
      dockerfile: ./../authentication-service/authentication-service.dockerfile
    restart: always
    ports:
      - '8081:80'
    deploy:
      mode: replicated
      replicas: 1
    environment:
      DSN: 'host=postgres port=5432 user=postgres dbname=users password=password sslmode=disable timezone=UTC connect_timeout=5'

  task-service:
    build:
      context: ./../task-service
      dockerfile: ./../task-service/task-service.dockerfile
    restart: always
    ports:
      - '8082:80'
    deploy:
      mode: replicated
      replicas: 1
    environment:
      DSN: 'root:password@tcp(mysql:3306)/tasks?charset=utf8&parseTime=True&loc=Local'

  mail-service:
    build:
      context: ./../mail-service
      dockerfile: ./../mail-service/mail-service.dockerfile
    restart: always
    deploy:
      mode: replicated
      replicas: 1
    environment:
      MAIL_DOMAIN: localhost
      MAIL_HOST: mailhog
      MAIL_PORT: 1025
      MAIL_ENCRYPTION: none
      MAIL_USERNAME: ''
      MAIL_PASSWORD: ''
      FROM_NAME: 'John Doe'
      FROM_ADDRESS: john.doe@example.com

  listener-service:
    build:
      context: ./../listener-service
      dockerfile: ./../listener-service/listener-service.dockerfile
    deploy:
      mode: replicated
      replicas: 1

  mysql:
    image: 'mysql:8.0'
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 'password'
      MYSQL_DATABASE: 'tasks'
    ports:
      - '3307:3306'
    deploy:
      mode: replicated
      replicas: 1
    volumes:
      - '/db-data/mysql/:/var/lib/mysql'

  postgres:
    image: 'postgres:14.2'
    restart: always
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'password'
      POSTGRES_DB: 'users'
    ports:
      - '5434:5432'
    deploy:
      mode: replicated
      replicas: 1
    volumes:
      - '/db-data/postgres/:/var/lib/postgresql/data'

  mongo:
    image: 'mongo:4.2.16-bionic'
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_DATABASE: logs
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - '/db-data/mongo/:/data/db'

  mailhog:
    image: 'mailhog/mailhog:latest'
    ports:
      - '1025:1025'
      - '8025:8025'

  rabbitmq:
    image: 'rabbitmq:3.9-alpine'
    ports:
      - '5672:5672'
    deploy:
      mode: replicated
      replicas: 1
    volumes:
      - '/db-data/rabbitmq/:/var/lib/rabbitmq'
