version: '3'

services:
  postgres:
    image: 'postgres:14.2'
    restart: always
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'password'
      POSTGRES_DB: 'users'
    ports:
      - '5434:5432'
    deploy:
      mode: replicated
      replicas: 1
    volumes:
      - '/db-data/postgres/:/var/lib/postgresql/data'
