# project/k8s/broker-service-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: broker-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: broker-service
  template:
    metadata:
      labels:
        app: broker-service
    spec:
      containers:
        - name: broker-service
          image: daffajatmiko/broker-service:1.0.1
          ports:
            - containerPort: 8080
          resources:
            requests:
              memory: '64Mi'
              cpu: '250m'
            limits:
              memory: '128Mi'
              cpu: '500m'
---
apiVersion: v1
kind: Service
metadata:
  name: broker-service
spec:
  ports:
    - protocol: TCP
      name: main-port
      port: 8080
      targetPort: 8080
  selector:
    app: broker-service
